### ISSUE TITLE
Replace the whole comment system with a tag system

### ISSUE THREAD

**Issue by ecwu** [UICHCC/uicCourse#39]

**Comment by ecwu** [comment]
Provide some tag ideas, please.

**Comment by lmy441900** [comment]
> Provide some tag ideas, please.

- Fun
- Rich Information
- Experienced teacher, humorous teacher
- Killer Inside (TM)

**Comment by ecwu** [comment]
Supplement: Every tag should assign a weight, to accumulate the overall score.

**Comment by ecwu** [comment]
Tough grader
Clear grading criteria
Extra credit
Graded by few things

Gives good feedback
Get ready to read
Participation matters

Lots of homework
Group projects
Beware of pop quizzes
So many papers
Test heavy

Accessible outside class

Respected
Inspirational
Hilarious
Caring

Skip class? You won't pass.

Lecture heavy
Amazing lectures

**Comment by lmy441900** [comment]
Teachers are not always bound with courses.

These tags are describing the instructor. Is this proper? (Or, if the teacher of course has changed, should these tags be all cleaned? In this case I think a new course should be created and the original one should be removed)

**Comment by ecwu** [comment]
So, the design of the tags will be very crucial.

BTW: All the tags which I commented on March 3 are found at RateMyProfessor website. Only for reference purpose.

**Comment by lmy441900** [comment]
> are found at RateMyProfessor website

They are rating for professors, but we are rating for courses.

**Comment by ecwu** [comment]
@lmy441900 
According to the DBMS knowledge we have learned, I have re-designed the tag model, so tags can be added later using the new dashboard. Now more important is to design a reasonable ‘sentiment index’ for each tag.

**Comment by ecwu** [comment]
Sentiment Index: According to the model design assumptions, sentiment_index is a floating-point number. When the value is positive, we believe that this label expresses positive emotions; when the value is negative, we believe that this label expresses negative emotions; when the value is 0, neutral emotions are expressed. This value will later be used in the course score model.

**Comment by ecwu** [comment]
There is currently no numerical limit on the `Sentiment Index`. Is it necessary to set the value range to `[-1,1]`?

**Comment by lmy441900** [comment]
> Is it necessary to set the value range to [-1,1]?

[-5, 5] may be better.
